### ISSUE TITLE
"VK_QUEUE_FAMILY_IGNORED" not found

### ISSUE THREAD

**Issue by GWRon** [davecamp/VulkanFirstDemo#1]
When compiling with BMX-NG, 32bit, release, gui I get:

```
Compile Error: Identifier 'VK_QUEUE_FAMILY_IGNORED' not found.
[C:/Users/Ronny/Downloads/VulkanFirstDemo-master/main.bmx;734;0]
```

**Comment by GWRon** [comment]
Of course it happens with the 64bit-build too. Just needed some time to compile modules ;-)

**Comment by davecamp** [comment]
I'll sync and update my local pub.mod...

**Comment by davecamp** [comment]
Using the pub.mod here, it should be working now.
I'm interested to know how it pans out with other gpus manufacturers as I only have access to an Nvidia gpu that has Vulkan drivers.

**Comment by GWRon** [comment]
Which pub.mod are you referring to?

I am using the most current NG-modules and bcc/bmk.

I downloaded your new revision but still got the same error. 


PS: GPU in the HP notebook (HP EliteBook 2760p) is Intel based.


Edit: Forget about the question, already found your pub.mod - wlll check now.

Edit2: Ok, compiled now - `Cannot find vulkan-1.dll` - seems I need to install something first. Maybe you should consider pull-requesting your constant-addition to the ng-pub.mod-repo.

**Comment by davecamp** [comment]
That's strange as

    VK_QUEUE_FAMILY_IGNORED

is here https://github.com/davecamp/pub.mod/blob/db98c8686b43fdc1d35190300b4f14843dc8f87b/vulkan.mod/vkApi.bmx#L45

**Comment by GWRon** [comment]
Already edited in ... I just did not see your pub.mod changes before (did not display the current changes in the overview until I clicked on the repo).

But the Intel HD 3000 seems to not be supported by Intels Vulkan drivers - so the only windows (10) computer here in the house might not be capable to test it. All others run Linux OSs

**Comment by davecamp** [comment]
Thats correct, I can also test with the same GPU too. Intel haven't released Vulkan compatible drivers for it just yet.

I don't have access to a Linux box here at work but I'll get it working later when I get home.
To test if your gpu(s) are compatible you can type 'vulkaninfo' into a terminal to give you some information.

**Comment by GWRon** [comment]
Seems Linux is out for me too: the newly introduced "AMDGPU-PRO Driver for Linux" which contains Vulkan support - does not support my GPUs. Seems 4-5 years is too old to be supported.

A pity - as I assumed "Vulkan" is not needing special hardware requirements (like a "DX12 hardware support").


So: Sorry, seems I cannot test your code here.

**Comment by davecamp** [comment]
Ok no worries, I'll close this for the time being.
Thankyou for trying and highlighting the missing Consts etc.
