### ISSUE TITLE
Setting up the Demo

### ISSUE THREAD

**Issue by lonnietc** [davecamp/VulkanFirstDemo#2]
Hello,

I am experimenting with BlitzMax for a GPU based 3D graphics project and have also just found out about BlitzMax-NG as well as have come across your Vulkan Demo.

Can you please tell me which version is need to run this and how to set it up to run.

I have BlitzMax on a Windows 10 (x64) system and have not yet figured out how to set up BlitzMax-NG which is supposed to have some improvements.

Thanks

**Comment by davecamp** [comment]
Hiya,

I apologise for the slow reply.

I believe I wrote the demo against the version 1 vulkan libraries.
The demo is super old now even developed an older version of Ng itself too.
Now that structs seem to be working more reliably in Ng you would have all of the '1 time use' Type(s), those that end with *Info should be converted to structs. This would save a ton of unnecessary garbage collection allocations by having those *Info struct(s) on the stack.

The demo was purely instrumental in showing the capabilities of Ng that it could work with the next-gen graphics APIs.

In a real program you would set up managers to manage the gpu resources dynamically as and when needed etc, which this demo most certainly does not do.
